apiVersion: 1.0
metadata:
  codeName: "com.hedon_haven.tester_external_dart"
  prettyName: "Tester as External (dart)"
  version: v0.3.2
  developer: "Hedon dev"
  contactEmail: "contact@hedon-haven.top"
  issueTrackerUrl: "https://github.com/Hedon-Haven/3rd-party-plugin-examples/issues"
  description: "A tester plugin written in dart for testing external plugins"
  updateUrl: "https://github.com/Hedon-Haven/3rd-party-plugin-examples/releases/latest/download/tester_external_dart-update.yaml"

providerData:
  iconUrl: "https://assets-cdn77.xvideos-cdn.com/v3/img/skins/default/logo/xvideos.black.svg"
  serviceUrl: "https://xvideos.com"
  handleUrls:
    - "https://xvideos.com/"
    - "https://www.xvideos.com/?k="
    - "https://www.xvideos.com/best/2026-08"
    - "https://www.xvideos.com/pornstars-index"

initialPageCounts:
  initialHomePage: 0
  initialSearchResultsPage: 0
  initialCommentsPage: 0
  initialVideoSuggestionsPage: 0
  initialAuthorVideosPage: 0
